services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cyberelk\Brofix\:
    resource: '../Classes/*'

  Cyberelk\Brofix\LinkAnalyzer:
    public: true

  Cyberelk\Brofix\Repository\BrokenLinkRepository:
    public: true

  # backend modules
  Cyberelk\Brofix\Controller\BrofixController:
    tags: [ 'backend.controller' ]

  # EventListeners
  Cyberelk\Brofix\EventListener\CheckBrokenRteLinkEventListener:
    tags:
      - name: event.listener
        identifier: 'rte-check-link-external'
        event: TYPO3\CMS\Core\Html\Event\BrokenLinkAnalysisEvent
        method: 'checkExternalLink'
      - name: event.listener
        identifier: 'rte-check-link-to-page'
        event: TYPO3\CMS\Core\Html\Event\BrokenLinkAnalysisEvent
        method: 'checkPageLink'
      - name: event.listener
        identifier: 'rte-check-link-to-file'
        event: TYPO3\CMS\Core\Html\Event\BrokenLinkAnalysisEvent
        method: 'checkFileLink'

  # Commands
  Cyberelk\Brofix\Command\CheckLinksCommand:
    tags:
      - name: 'console.command'
        command: 'brofix:checklinks'
        description: 'Check for broken links'
        hidden: false

